### ISSUE TITLE
discussion: Only check for status change when the browser window comes back into focus

### ISSUE THREAD

**Issue by ramfox** [qri-io/desktop#103]
We don't need to poll the backend if we decide that the polling status is too costly! We just need to listen for the browser onFocus event (not sure exactly what this would be for the electron window, but I'm sure it exists), and when we come back into focus we repoll for status/make another get request if the dataset is an fsi dataset.

**Comment by chriswhong** [comment]
Closing, polling will be phased out when websockets are implemented
