### ISSUE TITLE
repo: not found 

### ISSUE THREAD

**Issue by astroland** [qri-io/desktop#127]
when navigating to peer profiles, repo: not found error message displayed; no datasets available to see, even if they have published datasets in network repo listed

**Comment by b5** [comment]
hey @astroland! Thanks for filing. is this on app.qri.io by chance?

We're in a kinda weird in-between phase right now. Qri desktop is going to publish to a new website that isn't up yet.

**Comment by astroland** [comment]
this is on the desktop app.. Is there a 0.7.3 release? I think I may be getting these issues since I have the 0.7.2 release..I have to build it out - going to post on discord for help doing so. thank you!

**Comment by chriswhong** [comment]
Closing, this was related to the older `frontend`
