### ISSUE TITLE
compiled binary isn't starting backend

### ISSUE THREAD

**Issue by b5** [qri-io/desktop#149]
opening the app is bailing on "can't connect". We should also make sure log files from complied binary are writing to somewhere sane.

**Comment by dustmop** [comment]
We tracked the issue down to the qri command-line executable not having the +x bit set. So we should make sure that qri_install is setting this bit for osx.

I would also love to have better logging. Would be great to at least write "qri binary doesn't exist", "process failed to start", "process quit with the following message". Should we try using system logging here (like Console on osx, syslog on linux) or just pick some writable folder? We can't guarantee that $HOME/.qri exists yet.

**Comment by b5** [comment]
> I would also love to have better logging. Would be great to at least write "qri binary doesn't exist", "process failed to start", "process quit with the following message". Should we try using system logging here (like Console on osx, syslog on linux)

Very much agreed, and very much I think we should write to system logging location. I think that should be a separate issue

**Comment by b5** [comment]
I'ma mark this closed by qri-io/qri_install#15
