### ISSUE TITLE
should validate that "Save Path" is not a subset of "Data File"'s path

### ISSUE THREAD

**Issue by dustmop** [qri-io/desktop#205]
We should make sure we correctly message, and also enforce, that the Save Path is a separate location from where the "Data file" is being imported from. If the user is importing "~/datasets/new_ds/my_data.json", we should not allow the save path "~/datasets/new_ds/". This should be enforced on the backend as well, but the New Dataset dialog also needs to explain the meaning of these fields.

**Comment by uhLeeshUh** [comment]
Also adding to this - we received user feedback from Bob Gradeck in Sprint R re: confusion around "save path":

“When I checked out the dataset, there was some confusion about what is meant by ‘save path’”

**Comment by dustmop** [comment]
Sorry, I think the original issue is very out of date. This issue was filed back when the "New Dataset" dialog contained two separate paths, one for the input data file, and another for where to store the dataset's file components. Nowadays, that second step requires a "checkout", it isn't created automatically.

I do think there's some confusion with the term "Save Path" when doing a checkout. I think something better would be "Checkout Location" or something closer to what git uses.

**Comment by uhLeeshUh** [comment]
Gotcha, ok thanks for the clarity! I'll update the copy then and potentially add some help text
