### ISSUE TITLE
feat: drag and drop data files

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#240]
User can drag and drop a data file onto the new dataset modal, serving the same function as manually choosing the file using the file picker.

**Comment by ramfox** [comment]
We've discussed this internally and have an alternate flow for drag and drop:

From any location in qri desktop:
- User drags and drops a csv, json, geojson, or xlsx file into the app
- Qri automatically names the dataset based on the filename and inits the dataset based on the user's preferred dataset directory
- after ingest, desktop leaves you at the body view of the user's new dataset
