### ISSUE TITLE
feat: export a complete dataset version

### ISSUE THREAD

**Issue by b5** [qri-io/desktop#249]
It'd be great to wire up our export functionality so users can get access to prior versions of a dataset.

* User can command-click any version item in the dataset history pane, and choose a new option labelled "export this version"
* A Dialog should appear prompting the user to choose where to export the dataset, and have a button for export and a button for cancel
* clicking export should send a `GET` request to the backend `/export/:peername/:name/at/ipfs/:version` endpoint to export a dataset at that version
* This PR should also stub out an e22 test with comments that articulates the above flow. We should wait for a "initialized" e2e test setup before actually writing the test

**Comment by ramfox** [comment]
closed by #293
