### ISSUE TITLE
bug: rendering performance issues

### ISSUE THREAD

**Issue by ramfox** [qri-io/desktop#253]
Rendering large tables is expensive. When we switch to body, even though the data is already fetched from the backend, the process of rendering so many elements to the dom is causing the display to lag.

Rendering the body is also blocking other ui from changing. Critically, when a user clicks on the `Body` row, row isn't changing color, which signals to the user that the click never registered.

We need to ensure that the click is acknowledged right away. One idea is to pop open a little toast that says 'loading body' after the click, before we even signal to react to start rendering the body. Or we refactor to separate the dataset content top bar from the rest of the body content, and do something similar: create an action that would set that bar to indicate a loading state before the rendering even begins.

**Comment by chriswhong** [comment]
On further exploration last week, a big cause of the slowdown is that the data are already available for rendering complex components like the table and json viewer.  React isn't showing the selected tab change until the complex components are also done rendering.

**Comment by chriswhong** [comment]
Closing, body tables were refactored a while back and are stable
