### ISSUE TITLE
Add Dataset Modal needs UI for choosing a directory

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#258]
The Add workflow should create an FSI linked directory.

**Comment by ramfox** [comment]
Hi! just a note from when I was watching rico. Right now, when you add a dataset from the network, desktop assumes it doesn't have an fsi link so it changes the "activeTab" to history. Thinking we should remove this and drop into status, once we auto-create a fsi linked directory.

**Comment by chriswhong** [comment]
Added in 959a2cd5d8cc087d7514bb2767a5a2b47baa14a1
