### ISSUE TITLE
[8] API Call Loading & Error States + UI

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#27]
Loading States
- Add spinners where applicable to indicate that the app is fetching data

Error States
- Update the state tree on error
- Add UI for notifying the user when something has gone wrong

**Comment by ramfox** [comment]
#### for backend unavail
* [ ] add api status polling action which sets ui.apiConnection
* [ ] we should also catch if there is a 503 Service Unavailable error returned
* [ ] create AppError component, that explains the api cannot be reached and to restart the app
* [ ] on apiConnection === 0, show AppLoading, on apiConnection === -1  

#### create message and error toast
* [ ] create Toast component, with alternate styling for error and message
* [ ] create setMessage(message: string) call that has a timeout to reset after a few seconds
* [ ] create setErrorMessage(error: string) call with no timeout

**Comment by ramfox** [comment]
So thinking about this issue.

I think this is actually a few issues.

- design the Toast for message and error message.
- design the `Backend unavailable` component.
- create actions for message, error message, and apiConnection
- wire everything up and test

And then I think there is a whole separate issue for how we are handling loading spinners and loading states throughout the app when there is no pagination (our discussion in office yesterday).

I'm going to make a separate issue for just the appUnavail/Toast stuff. I think it also belongs in our sprint. Then this issue can be used to track the Mutations stuff we were discussing.

**Comment by ramfox** [comment]
The 3 places where we are going to get loading an error state:

#### Entire app
`ui.appConnection`
(0 means attempting to connect, -1 means not connected)

#### Pagination
All paginated values will have pagination information alongside it
`isFetching`: is it loading?
`error`: was there an error

#### Mutations
This is for when we submit to the api
They live in `state.mutations`
`state.mutations[NAME].values`: the params or info needed to submit the POST request
`state.mutations[NAME].isSubmitting`: loading state
`state.mutations[NAME].error`: any error message
Once the state has returned with success, we can clear the mutation.

**Comment by chriswhong** [comment]
I am currently implementing loading and success state for saves in #40, and want to try to get a toast in for this issue.  I'll design it to be usable throughout the app and it will satisfy the toast item in this issue.

**Comment by ramfox** [comment]
Great, pulling it out now into a separate issue!
