### ISSUE TITLE
[3] Open Dataset Location/Link this Dataset Button

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#29]
When the working dataset is unlinked in the filesystem, we should prompt the user to link it with a button.

Link this Dataset -> Opens a modal allowing the user to specify where on the filesystem they would like to create a linked dataset directory

When the working dataset is linked, we should
- show the path to the linked directory
-  prompt the user to reveal the location in their OS' GUI

**Comment by ramfox** [comment]
After discussion, Link this Dataset doesn't need a modal. We should just open the file picker and let the user select/create a folder to which they want the dataset linked. The dataset should then be checked out in the fs.

**Comment by dustmop** [comment]
If I'm understanding this correctly, this requires an api endpoint for "checkout" on the backend, right? It should accept the name of the dataset that already exists in the user's repo, plus the filesystem location to check it out to.
