### ISSUE TITLE
Port react storybook to this repo

### ISSUE THREAD

**Issue by b5** [qri-io/desktop#291]
We’re big fans of [storybook](https://github.com/storybooks/storybook), and would love to get a storybook implemented in this repo. This would give us an environment to experiment with & extend components & a place to iterate on different flows.

This PR starts simple: introduce storybook to our codebase with a simple story around our existing Button component. After this PR the next step would be to turn out a `Stylesheet` component as a story to track styling across the app. 

@jlwaugh previously implemented this for us on our prior repo: qri-io/frontend. This time around we need to do it with typescript. The storybook implementation in that repo should serve as a guide.

### PR1: Steps to complete:
* follow https://storybook.js.org/docs/guides/guide-react/
  * manually add the storybook dep to our dev dependencies
  * add an entry to `package.json` scripts, as outlined in the guide
  * follow the steps for adding a simple button, but use _our_ button component instead
* add a new section to README.md called "Qri Storybook" linking to what the storybook is, and give quick steps to open the storybook
* open PR & 🎉

**Comment by chriswhong** [comment]
Storybook is in!  Closing
