### ISSUE TITLE
feat: Add Readme (Qri Desktop)

### ISSUE THREAD

**Issue by ramfox** [qri-io/desktop#296]
Update 10/21/19 (chriswhong):

This issue will refactor qri's `viz` component as `readme`.  

- In `status` mode, users can edit markdown and preview it, and can make commits as they would with any other component change.
- In `history` mode, users can inspect the markdown or the preview as read-only

Original issue:

The component will behave just like others 

-  add 'Viz' component
- should have a basic codeviewer with html syntax highlighting
- view visualization button!
- opens iframe that shows the viz
-  icon maybe `chart-area` from font awesome?
- add Viz component to DatasetComponent component
- Should we show viz file greyed out when it doesn't exist, or should we not show it at all?
- adjust Dataset's ComponentDidUpdate. perhaps refactor out so logic can be reused/is more clear what is happening.
- adjust SelectedComponent model
- adjust initialState for workingDataset and commitDetails? Should initialState have a transform?
- adjust chooseDefaultComponent

**Comment by chriswhong** [comment]
Updates from sprint planning: 

Qri desktop should include a new readme component tab, placed at the top of the component list in both status and history modes

In status view, the content area should default to a full height and width text area with a toolbar for adding markdown to text the user has entered (similar to github’s markdown editor, clicking the B button in the toolbar adds ** on either side of the selected text.)

User can toggle a “preview” mode to see the rendered html.  This should get the rendered markdown from Qri (It should not render the raw markdown client-side)

In history view the default view is the rendered html for the readme.  User can toggle to see the raw markdown, but of course they cannot edit it.

Consider the need to show diffing at a later date (it may make more sense to show a diff-friendly code editor when viewing the markdown in history mode)

Feature doc: https://docs.google.com/document/d/1LHvjRgSN9q_pFWZ_lBOUtjIhSO0-4M-Mxj8AeX9IcxU/edit#
![Artboard Copy 2](https://user-images.githubusercontent.com/1833820/67402947-49d72900-f57f-11e9-8160-ce946b4e02ef.png)

![Artboard](https://user-images.githubusercontent.com/1833820/67402931-45ab0b80-f57f-11e9-907e-be8047173026.png)
