### ISSUE TITLE
Updating dataset title and saving doesn’t update title in dataset picker in the header

### ISSUE THREAD

**Issue by Mr0grog** [qri-io/desktop#303]
I have this dataset: https://qri.cloud/mr0grog/edgi_webmonitoring_changed_terms_top, and I added a commit to shorten the title from “EDGI Web Monitoring: Top Changed Terms on All Pages” to “EDGI Web Monitoring: Top Changed Terms”.

<img width="521" alt="unchanged-title" src="https://user-images.githubusercontent.com/74178/67431990-3f765880-f59a-11e9-8411-2c7095d0aea1.png">

Refreshing with `cmd+R` solves the problem, but is not great to do.

**Comment by chriswhong** [comment]
Thanks for flagging this @Mr0grog.  

We need to trigger a refresh of the dataset list when `meta.title` is changed.

**Comment by chriswhong** [comment]
Still open, we should revisit this in collection view refactoring

**Comment by ramfox** [comment]
Closed
