### ISSUE TITLE
Body view refactor

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#308]
Three types of bodies that have different rendering concerns:

1. Tabular (csv, json array of objects with depth of 2, xlsx)
2. JSON Array of Objects with depth greater than 2 (related to #302)
3. JSON Object (A geojson FeatureCollection is an example of this)

Preliminary work has been done on the branch `json-performance` to use `react-window` for higher performance scrolling of item 2 above. 

HandsonTable is working, but feels slow/unresponsive at times.  Adding a page of data makes the app crawl, presumable due to the calculations necessary to determine column width, etc

An alternative approach may be to also use `react-window` but use html tables to offload the layout calculations.

#1 and #2 should be designed and optimized to provide a smooth UX for pagination (#1 does this now with a toast, #2 does not.  We should avoid the toast and go with some other loading state indicator when pagination is firing)

We can de-prioritize # 3, and use codemirror or just `JSON.stringify()` to show everything (this assumes no pagination)

**Comment by b5** [comment]
@ramfox do you think #313 made enough progress to call this closed?

**Comment by ramfox** [comment]
yes! closed by #313
