### ISSUE TITLE
Readme cursor continually bumped to top row.

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/desktop#345]
While composing a readme, Mika's  @MikaAust cursor was kicked back up to the very top row while she attempted to add text (several times). She had successfully added a first line of text, under which she built a list of 15-20 items.  Under the list she tried to give herself a space or two of buffer before adding another line, and at that point her cursor was kicked back up to the very top row.

**Comment by ramfox** [comment]
Seems to be related to issues when saving the readme data to the filesystem. When the page re-renders looks like the cursor jumps back to the top... that's my first best guess.

**Comment by MikaAust** [comment]
Good evening Kasey,

    Yes when I am typing readme data, the cursor jumps to the top in the
middle of me typing my description in the readme portion.
