### ISSUE TITLE
Image Overlay

### ISSUE THREAD

**Issue by amandabNYC** [qri-io/desktop#346]
I am experiencing image overlays in QRI on the Meta and Structure pages (some images attached).

<img width="800" alt="Qri2" src="https://user-images.githubusercontent.com/41880533/69599368-c45df300-0fda-11ea-8df1-de58225d851c.png">
<img width="677" alt="Qri1" src="https://user-images.githubusercontent.com/41880533/69599370-c627b680-0fda-11ea-9bf3-b6c57e1e3c8c.png">
<img width="697" alt="Qri3" src="https://user-images.githubusercontent.com/41880533/69599622-b78dcf00-0fdb-11ea-86fd-c6d6b4711b51.png">

**Comment by ramfox** [comment]
Hey! Thanks for filing this issue.

Some questions just to narrow down the problem:

- What was the flow (what did you click on or what actions did you take) that got you to this spot?

- Was this the first time you added a dataset to Qri Desktop?

- If not, is this the first time adding a dataset to this version of Qri Desktop?

- When you try refreshing the page, does it fix the problem (ctrl + R)

That will help narrow down what's going on :)

Thanks!

**Comment by amandabNYC** [comment]
Hello Kasey,

Please see below.


>    -
>
>    What was the flow (what did you click on or what actions did you take)
>    that got you to this spot?
>
> We were showing Rico our knowledge of loading datasets into Qri. I
uploaded a set and then were were going through every tab - that's when we
noticed the overlay.

>
>    -
>
>    Was this the first time you added a dataset to Qri Desktop?
>
> No

>
>    -
>
>    If not, is this the first time adding a dataset to this version of Qri
>    Desktop?
>
> Yes

>
>    -
>
>    When you try refreshing the page, does it fix the problem (ctrl + R)
>
> No - I created another dataset and noticed the same issue. I closed and
restarted Qri, and the issue remained.

Regards,
Amanda Baird

Link to me at: https://www.linkedin.com/in/amandabaird
<http://www.linkedin.com/in/amandabaird/>

**Comment by ramfox** [comment]
thanks @amandabNYC that super helps!!

**Comment by ramfox** [comment]
This has been fixed in the last release!
