### ISSUE TITLE
"Directory not empty" error on dataset remove

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#351]
When attempting to remove a dataset in Qri Desktop, I've seen a red error in the remove modal indicating that the directory is not empty.  However, the dataset has actually been removed from qri.  The final step of removing the working directory fails because of the existence of files qri is not familiar with.  (.DS_Store in my most recent case)

**Comment by ramfox** [comment]
Hmmm... interesting.  Since it's a hidden file a lay-user might be confused why the folder itself wasn't deleted. 

This might actually a be a Qri backend issue, where we refine the error returned so the desktop app can handle properly.
