### ISSUE TITLE
Dataset Rename UI

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#353]
User can rename the currently selected dataset by clicking on the name.  

- Hover over dataset name should show that it is editable (maybe show a pencil on hover)
- Click on dataset name should turn the name into a text entry field
- Enter or Tab key should blur input
- Escape key should abandon changes and restore the original name.  
- Handle errors (if the backend says the name is unavailable, show the user why, remain in edit mode)

**Comment by ramfox** [comment]
closed by #357
