### ISSUE TITLE
Streamline Dataset Creation

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#354]
Drag & Drop
 - POST file location to backend, backend will create dataset with initial commit (no working directory) and respond with the dataset name
- Frontend sets `workingDataset` to the new dataset, lands user on history tab > Body

File Menu or Cmd-N
 - Refactor Create Dataset Modal to include *only* a file picker.  
 - Same steps as above

**Comment by dustmop** [comment]
> * POST file location to backend, backend will create dataset with initial commit (no working directory) and respond with the dataset name

This is working now, as of https://github.com/qri-io/qri/pull/1039. You can POST to `localhost:2503/save/?bodypath=[path to file]&new=true`. The request needs to have `Content-type` of `application-json` and a body with an empty json object `{}`.

**Comment by ramfox** [comment]
closed by #362
