### ISSUE TITLE
Peername and name not populating in checkout modal

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#371]
Check out modal title just says "Link /", peername and name are missing.
Also, the text should be reworded to say "Checkout" instead of "Link"
<img width="1300" alt="Screen Shot 2019-12-13 at 10 39 27 AM" src="https://user-images.githubusercontent.com/1833820/70812154-12be1080-1d95-11ea-8d67-8b4f4cc0d3f3.png">

**Comment by ramfox** [comment]
Can't consistently re-create this bug. But did change 'link' to 'checkout'
