### ISSUE TITLE
Problem creating a new dataset on Mac

### ISSUE THREAD

**Issue by hampelm** [qri-io/desktop#395]
I downloaded the desktop app for mac (0.3.1) and created an account.

I clicked "Created a Dataset" and selected a CSV file in my downloads folder. The "Source data file" field did not get filled in and the "Create Dataset" button stayed inactive. I tried a couple files and restarting the app, no dice. 

I see this in the console: 
```
Uncaught (in promise) Error: no peername or name selected
    at bundle.js:65
    at l (bundle.js:42)
    at Generator._invoke (bundle.js:42)
    at Generator.forEach.e.<computed> [as next] (bundle.js:42)
    at l (bundle.js:42)
    at t (bundle.js:42)
    at bundle.js:42
    at new Promise (<anonymous>)
    at i (bundle.js:42)
    at k._invoke (bundle.js:42)
app.production.html#/dataset:1 Form submission canceled because the form is not connected
app.production.html#/dataset:1 Uncaught (in promise) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112)
    at Object.basename (path.js:1157)
    at L (bundle.js:65)
    at bundle.js:65
app.production.html#/dataset:1 Form submission canceled because the form is not connected
```

**Comment by ramfox** [comment]
hey @hampelm thanks for filling this!

Can you do me a favor and try creating a dataset by dragging and dropping the csv into the app rather then using the "create dataset" modal? Just want to double check that.

In the version at master right now, this "create dataset" modal bug has been fixed. If you can indeed create a dataset via drag and drop to confirm that this isn't some underlying issue, I'll consider this issue closed.

**Comment by hampelm** [comment]
Ok drag and drop seemed to do the trick 👍
