### ISSUE TITLE
Top bar menu items use wrong font

### ISSUE THREAD

**Issue by Mr0grog** [qri-io/desktop#423]
In Desktop v0.3.3 (MacOS v10.14.6), the text for buttons arranged along the top of the window is showing up as the default font, rather than one that matches the rest of the application:

![qri-topbar-font](https://user-images.githubusercontent.com/74178/73210229-ad34a200-40fe-11ea-81c1-1a50ae5c3c5d.png)

It’s looks like the rest of the app uses “Avenir,” “Rubik,” “Avenir Next,” and then various system fonts in order of what’s available, but the topbar is just “Rubik” or the default font. Rubik also isn’t being loaded (I can confirm that the rest of the type in the app appears to be Avenir), but I’m not sure whether that’s currently intended or is also a bug.

**Comment by ramfox** [comment]
closed by #419
