### ISSUE TITLE
About menu item disabled at application launch

### ISSUE THREAD

**Issue by Mr0grog** [qri-io/desktop#424]
Using desktop v0.3.3 on MacOS v10.14.6, the “Qri Desktop” → “About Qri Desktop” menu item is disabled when I first launch the application:

<img width="769" alt="About-menu-item-disabled" src="https://user-images.githubusercontent.com/74178/73210680-9b073380-40ff-11ea-8b18-0ea0396caa9d.png">

Clicking on a button that launches a modal doesn’t change that, but clicking any of the buttons in the sidebar makes it active. (Surprisingly, that includes the “support” button that launches Discord in a browser, which otherwise doesn’t seem to affect anything in the app.)

**Comment by ramfox** [comment]
closed by #419
