### ISSUE TITLE
Timed out when trying to sign in

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/desktop#451]
<img width="1023" alt="Screen Shot 2020-02-17 at 10 29 20 AM" src="https://user-images.githubusercontent.com/28312271/74667048-9e2a9800-5170-11ea-833b-35217de561ba.png">

**Comment by b5** [comment]
Looks like your registry is configured to point to a strange location. Try running this from the command line:

```
qri config set registry.location https://registry.qri.cloud
```

That should fix it!
