### ISSUE TITLE
Replacing checked out body.csv does show up as a change until app restart

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#459]
Observed in 0.3.6_dev:

1) Working with an existing dataset that was already checked out (https://qri.cloud/chriswhong/nyc_open_data_portal_datasets)
2) Replaced `body.csv` with a different csv (deleted `body.csv`, moved new csv into directory, renamed to `body.csv`)
3) Switching back to Desktop, there is no indication of change and I cannot commit.
4) Reloading with Cmd-R does not help, but after quitting and restarting the app, the change shows up and I can commit.

Attempted a 2nd time and observed the same thing.

**Comment by dustmop** [comment]
Cannot reproduce this, the steps you described worked okay for me. Are you running the backend built from head, or is it an old version?

**Comment by dustmop** [comment]
Verified that the problem was an old build of the qri backend. The packaged Qri Desktop.app will run the binary in its Resources/backend folder, not the one built using "go install".
