### ISSUE TITLE
feat: forgot password

### ISSUE THREAD

**Issue by andrew** [qri-io/desktop#477]
I can't seem to find a way to reset/recover a previous account that I had, would be great to see a "forgot password?" link on the sign in page of qri desktop.

**Comment by b5** [comment]
Apologies for the delay on this @andrew, can't believe it took us this long to get resets in place, but they're now up if you'd like to give it a try. I'll close this, but if the new reset flow doesn't work for you, or you think we could improve it in some way, please feel free to re-open.

**Comment by b5** [comment]
I should mention, the actual password reset functionality is on https://qri.cloud

If you click sign-in, there's a `Forgot Password` link in the sign-in modal. Full URL is: https://qri.cloud/signin/forgot
