### ISSUE TITLE
Unsupported value: +Inf

### ISSUE THREAD

**Issue by xxristoskk** [qri-io/desktop#478]
Creating a dataset that contains tweets, the Desktop version fails to load the CSV. Exploring further, I'm getting this error in the CLI: 

> validating data: error reading values: error writing row 129283: json: unsupported value: +Inf

Row 129283 contains a tweet with a few emojis. There are emojis in other rows that work, but this one might have one too many.

**Comment by b5** [comment]
Thanks for filing @xxristoskk! Could you by chance pull out just row 129283 & paste it here?

**Comment by xxristoskk** [comment]
@b5 I figured out where the issue was--it wasn't the emojis at all. I'm using a Pandas DataFrame to clean/analyze the dataset, and also to convert the DataFrame to CSV. During that conversion, some of the data types get messed around with, and some zeros were turned into Numpy infinite. After changing those back to 0, I was able to commit just fine.

**Comment by b5** [comment]
Fantastic! Glad to hear you were able to find a solution. I'm going to mark this as closed.

Thanks to your filing this issue, we've uncovered _another_ issue around how we handle stuff like `+Inf`, so double thank-you @xxristoskk!
