### ISSUE TITLE
Checking out a dataset that is already linked still creates a new directory

### ISSUE THREAD

**Issue by Mr0grog** [qri-io/desktop#480]
If I have a dataset with a linked directory that I checkout out via the CLI, Qri Desktop still shows a “checkout” button. Trying to check it out to a new directory in Desktop rightly shows an error that it’s already checked out somewhere else, but it still creates an empty directory at the new checkout location. It would be much better if it didn’t change anything on disk in this situation.

Steps to reproduce:

1. Create or checkout a dataset somewhere on disk with Qri CLI.
2. Open the dataset in Qri Desktop.
3. In Qri Desktop, click the “checkout” button and set the save path to a different directory than the one used in step 1.
4. Qri Desktop shows an error (`'<dataset name>' is already linked to <path from step 1>`), but also creates an empty directory at the path from step 3.

Expected:

Nothing at all in the path specified in step 3.

(Or even better, if Desktop detected the dataset is already linked ahead of time and didn’t show a checkout button at all.)

Qri Desktop version 0.4.0.

**Comment by ramfox** [comment]
Thanks for this :)

This is actually an error for qri backend, I'll file the issue.

Although with a fix to #480 hopefully a user isn't ever in a place to get to this point
