### ISSUE TITLE
2D Schema Layout

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#49]
Add a layout to the `Schema` component, visually showing the schema.

**Comment by chriswhong** [comment]
We should consider borrowing code from jsonschema.net:

<img width="1433" alt="JSON_Schema_Tool" src="https://user-images.githubusercontent.com/1833820/62432785-896c4280-b6ff-11e9-8781-3ed087107f1e.png">

**Comment by ramfox** [comment]
punted from sprint O

**Comment by chriswhong** [comment]
Sprint S Update:  Add a simple presentation-only table layout for 2D schemas.  If the schema is not 2D, show JSON (as we are doing now for all schemas)
