### ISSUE TITLE
Typing in commit title/message fields always appends at end

### ISSUE THREAD

**Issue by hbruch** [qri-io/desktop#496]
Trying to add some text in the middle of already entered text in the commit title/message fields will transfer the cursor to the end of the already entered text after the first char is typed.

**Comment by rustprooflabs** [comment]
I encountered this bug today when trying to make minor updates to a long commit message.  I placed the cursor in the middle of the text where edits were needed.  The first typed character is in the appropriate place then the cursor jumps to the very end of the message for the second character and beyond.

Desktop version 0.4.2.

**Comment by Mr0grog** [comment]
I also hit this while creating a new dataset today, and was briefly confused by the gibberish in my commit message when I finished typing. 😜
