### ISSUE TITLE
Export creates a zip in a directory

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#538]
In v0.4.1, choosing "Export this version":

The OS file picker opens, I specify foo.zip on my Desktop
After clicking save, a directory called foo.zip is added to my Desktop.
Inside /foo.zip is a zip file with an autogenerated name: nyc-transit-data-turnstile_daily_counts_2019-04-04-2020-08-04-24-am.zip
What I expected to happen:

Desktop should create foo.zip, a zip file on my desktop, containing the dataset's files.

**Comment by b5** [comment]
Let's hijack this issue to work on a better export button!

**Comment by uhLeeshUh** [comment]
As an update for this issue - I can't reproduce this nested zip error, but it did bring about the needed change of updating the export URL to reflect our new get endpoint
