### ISSUE TITLE
Boolean values not displaying in web preview

### ISSUE THREAD

**Issue by rustprooflabs** [qri-io/desktop#548]
Boolean columns in dataset do not display values in the web based preview.  It does render properly in Qri Desktop (0.4.2).  [Example dataset](https://qri.cloud/rustprooflabs/dbeaver_srid_render) includes `renders` column, all rows have either T/F, no NULL.

Screenshot in browser, empty `renders` column:

![image](https://user-images.githubusercontent.com/3085224/81603353-6e63e880-938b-11ea-82ab-d325dd88441b.png)

Screenshot in Qri Desktop, showing boolean values.

![image](https://user-images.githubusercontent.com/3085224/81603385-7b80d780-938b-11ea-9155-5d8963558919.png)

**Comment by VarsMolta** [comment]
happy to work on this. whats the code repo for the web portion of this? sounds like a `good-first-issue` to work on

**Comment by chriswhong** [comment]
Closing addressed in #166
