### ISSUE TITLE
Unable to edit dataset when list of commits reaches a certain number

### ISSUE THREAD

**Issue by VarsMolta** [qri-io/desktop#551]
In the QRI desktop, by default the `History` tab on the left is highlighted when editing a local dataset. When the list of commits in this history tab is long enough, I'm unable to click on the `Status` tab to start editing my dataset. The only way to fix this is to maximize the window, at which point I can resume editing. But this too reaches a limit beyond which i can't edit anymore. See screenshot
<img width="545" alt="Screen Shot 2020-05-18 at 11 24 58 AM" src="https://user-images.githubusercontent.com/3681555/82230814-3cf29c00-98fa-11ea-9f91-2e9558b65848.png">

**Comment by chriswhong** [comment]
We've got a fix up for this in #587.
