### ISSUE TITLE
docs(readme): update dev section to spell out some idiosyncrasies 

### ISSUE THREAD

**Issue by ramfox** [qri-io/desktop#558]
Let's make it easier to onboard yourself as a qri desktop dev. Going to make a list here of topics that should be expanded/noted in the DEVELOPER docs:

- [x] how/in what order qri desktop looks for the qri backend
- [x] workaround for installing `temp_registry_server` if `go get` command isn't working (& make sure to add to your PATH)
- [ ] basic understanding of what a qri repo is and what QRI_PATH and IPFS_PATH are

#### notes:
Qri desktop relies on the [Qri backend](github.com/qri-io/qri). These are the locations that desktop will look for the backend on your machine:
1) is there a qri node already running? If yes, just use that node.
2) is there a qri binary already installed on your `PATH`? If yes, use that binary.
3) do i have qri internally (at /desktop/backend/qri)? Use that! Desktop comes packaged with this binary, and will look here as a last resort. For many desktop users, however, this is the only version of Qri they may have.

**Comment by uhLeeshUh** [comment]
Here is the link to the doc I made about Qri path vs. Qri binary learnings: https://docs.google.com/document/d/12PDXcdirsB8ypd6wNADPKTBq48ztCC_i5-jwKNF3_v0/edit?usp=sharing
