### ISSUE TITLE
Desktop should switch off of `export` and use `get` instead

### ISSUE THREAD

**Issue by dustmop** [qri-io/desktop#568]
Original discussion here: https://github.com/qri-io/qri/issues/1176

Short version: it's confusing for `qri` core to have both `get` and `export` commands, since the original motivation for having both no longer fits. We want to delete the `qri export` command, and have already moved its primary functionality into `qri get --format json` command. We should switch desktop to call `/get?format=json` instead when the user tries to export a dataset.

There's at least one known bug with `qri get --format json`: https://github.com/qri-io/qri/issues/1339, if there are other bits of functionality missing we should add them to qri core's method so that Desktop is happy and has what it needs.

Issue for qri core: https://github.com/qri-io/qri/issues/1441

**Comment by ramfox** [comment]
https://github.com/qri-io/desktop/blob/866a9e4c37473b4a35f039a7ead474705ef94bb4/app/components/modals/ExportVersion.tsx#L42-L52

On desktop, asking to export something is actually triggering a download. This is different from any other action we use, so the whole thing is controlled by the `ExportVersion` component, with some coordination between the renderer and main processes. 

We use the URL defined above (which should potentially be the only thing you need to edit, as it include the query params in the URL string). For your knowledge (or if something goes wrong and you need some clues as to where to look), the actually request goes off when we click the "export version" button. It fires off the `handleSubmit` function, which is actually the renderer process sending an "export" event w/ `args` to the main process (also above).

The main process catches it here: 
https://github.com/qri-io/desktop/blob/866a9e4c37473b4a35f039a7ead474705ef94bb4/app/main.development.js#L514-L519

Hope this helps!

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/desktop/pull/573.
