### ISSUE TITLE
Status Pane and Display-only Views

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#6]
In the Status Pane, users can click on a file in the list, and see details about that file's status in the main content area.  

- Design/Layout 
- - List Items, with symbology to reflect the same information provided by qri status (changed/unchanged, valid, etc)
- - Meta View Display-only Content & Layout
- - Schema View Display-only Content & Layout
- - Body View Display-only Content & Layout

-  Implementation
- - Data Store prep (get the data from the API in the store in the desired format)
- - List Item Component
- - Display-only Meta View
- - Display-only Schema View
- - Display-only Body View

**Comment by ramfox** [comment]
closed by #12 #23
