### ISSUE TITLE
"New Dataset" Modal Component

### ISSUE THREAD

**Issue by b5** [qri-io/desktop#601]
There should be a `New Dataset` button in the collection view. When click it should prompt for dataset title (dataset name can be derived from title).  UI can create a compatible dataset name as the user types the title:

<img width="412" alt="Screen Shot 2020-09-28 at 11 24 48 AM" src="https://user-images.githubusercontent.com/1154390/94452180-40861180-017d-11eb-8445-db2a7ed78ca0.png">

This issue _only_ defines the creation of the modal & `Create` click handler. actual nav will be in a separate issue

### Steps to Complete
* [x] create a `nameFromTitle` utility function that interprets human titles into a valid dataset name
* [x] write a test for `nameFromTitle` that confirms proper name handling
* [x] create the `NewDatasetModal` component with appropriate modal styling
* [x] add Modal to react storybook
* [x] use `nameFromTitle` in the component to derive a title on input change for the user
* [x] `NewDatasetModal` should have an `onClick` handler that gives a `Dataset` arg to the callback with the dataset name, and `meta: { title: "user-generated-title" }`

**Comment by ramfox** [comment]
We already have a new dataset modal, it just needs to be altered.

<img width="513" alt="Screen Shot 2020-09-28 at 12 10 38 PM" src="https://user-images.githubusercontent.com/17440142/94458279-b9886780-0183-11eb-9cc2-5012d29fa7f1.png">

the component exists at `/app/components/modals/CreateDataset`
