### ISSUE TITLE
use websocket progress events to update state tree

### ISSUE THREAD

**Issue by b5** [qri-io/desktop#605]
We've refactored the websocket connection between desktop & backend to be a feed straight off the event bus, it now  uses a set of constants that live here in desktop:

https://github.com/qri-io/desktop/blob/493a288e27cfb9cd281b7d48f64166040b295117/app/store/wsMiddleware.ts#L17

We want to use those events to show dataset push & pull progress. Basically a desktop-side version of this:

https://github.com/qri-io/qri/blob/2d68e7a45a01ec6bdb42b0fb8038f53c8f929473/remote/client.go#L759

So to start, we need state-tree syncing to these events so we can build UI on it. we should update desktop to listen for these same in `weMiddleware.ts` and update a  new section of the state tree when they appear. We'll build UI to display them once the events are up

**Comment by Arqu** [comment]
Just a few things to understand this better:
- Do we want to have just 1 app wide progress bar and technically you can't start multiple pulls in paralel? Or do we need to keep progress per action and have UI figure out how to use that?
- @ramfox Where should this state live, if its UI wide in the UI state? If it's /dataset, is this attributed to workingDataset or just Dataset?

**Comment by ramfox** [comment]
hmmm offhand I'd say...

new reducer! `ProgressReducer`?, it takes an array of `ProgressDetails`?

```
export interface ProgressDetails {
  username string
  name string
  percentComplete number
  type string // like push, pull, or something, if we need it
  ... other progress stuff we need
}

export interface ProgresssStore {
  progress ProgressDetails[]
}

const initialState: ProgressStore {
  progress: []
}

```
