### ISSUE TITLE
wire collection list view bulk action buttons to real actions

### ISSUE THREAD

**Issue by b5** [qri-io/desktop#616]
building a selection of datasets presents three options to the user:

* [ ] quick export CSV
* [x] pull latest
* [x] remove

Each of those currently is just wired up to an `alert` call. Thy need to be hooked up to new actions that perform corresponding bulk operations

**Comment by ramfox** [comment]
claiming batch remove!!!

**Comment by ramfox** [comment]
For batch export:
- we are assuming quick csv export, correct? Which means we should just be showing the save dialog & having each csv save in that location

For batch remove:
Assuming we still have the confirm modal pop up, assuming that we should generalize the "if fsi checked out, should we keep the files" check box, & have all datasets that are fsi checked follow that preference
