### ISSUE TITLE
[8] No datasets selected screen

### ISSUE THREAD

**Issue by ramfox** [qri-io/desktop#95]
We need a page where a user can land when they don't have any datasets selected.

This screen should have some nice splash art and have calls to action:
- add a dataset
- link a dataset
- create a dataset
- choose a dataset
- links to docs

Sidebar should be empty. (no status no history)
Sidebar header should go from 'current dataset' to 'choose a dataset'.
Publish/link etc buttons should disappear.

Users can get to this page when:
- the first time they ever open the app
- anytime the selection is cleared
- the dataset that is currently selected returns with an error (should also clear the selection)
- in the dataset list, they click on the sidebar header (that says current dataset)

**Comment by chriswhong** [comment]
Move the existing No Datasets view from being its own route to being content for the main content area.  

Tabs remain active but show empty lists.
